### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-train-test-gha#16]
Failure in `cross_validation_results.py` [here](https://github.com/RasaHQ/rasa-train-test-gha/blob/63f15568983d817ffa5487bddbffa3a1d64cd126/scripts/cross_validation_results.py#L20). Running under `3.0.8`.

When run locally, the `intent_report.json` is generated.

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/RasaHQ/rasa-train-test-gha/main/scripts/cross_validation_results.py", line 70, in <module>
    intents = intent_table()
  File "/home/runner/work/_actions/RasaHQ/rasa-train-test-gha/main/scripts/cross_validation_results.py", line 20, in intent_table
    data.pop("accuracy", None)
UnboundLocalError: local variable 'data' referenced before assignment
Error: Process completed with exit code 1.
```

Pipeline is auto-generated:

```yml
# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
```
