### ISSUE TITLE
Add ability to fine-tune.

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa-train-test-gha#3]
Currently `rasa train` step trains a model from scratch. With [incremental training](https://rasa.com/docs/rasa/command-line-interface#incremental-training) we introduced the ability to use a previously trained model and continue training it on additional data points collected. In the simplest case, this can be done by `rasa train --finetune`. It would be good to include this in the list of possible commands as part of this action so that [users can make use of incremental training in CI/CD pipelines](https://forum.rasa.com/t/rasax-incremental-model-training/42207) as well.

**Comment by gurjmatharu** [comment]
I'd like to add the ability to select the folder structure as well.  Currently we have split our training files up and it seems that it doesn't pick it up.

**Comment by HotThoughts** [comment]
@gurjmatharu hey just want you to know that we just released 2.0. You can now pass arguments to `rasa test core` and `rasa test nlu` separately. For example,
- use `test_nlu_args` to set the file or folder containing your NLU data
- use `test_core_args` to set the file or folder containing your test stories

```yaml
jobs:
    train_and_test:
        # ...
        steps:
            # ...
            - name: Train and Test Rasa Demo
              id: action
              uses: RasaHQ/rasa-train-test-gha@main
              with:
                # List of available tags: https://hub.docker.com/r/rasa/rasa/tags
                rasa_version: '2.0.0-full'
                test_nlu_args: '--stories test/test_stories.yml'
                test_core_args: '--nlu data/'
                # In order to add a PR comment with summary
                # a GH Token has to be pass to the GH action
                github_token: ${{ secrets.GITHUB_TOKEN }}

```
